checks:
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 10

plugins:
  eslint:
    enabled: true
    channel: "eslint-7"
    config:
      config: ".eslintrc.yaml"

ratings:
   paths:
   - "**.js"
