env:
  es6: true
  node: true
  mocha: true
  es2020: true
  es2024: true

root: true

parserOptions:
  sourceType: module

extends:
  - eslint:recommended

rules:
  no-unused-vars: [error, { args: none }]
  dot-notation: error
  prefer-const: warn
