env:
  es6: true
  node: true
  mocha: true
  es2020: true
  es2024: true

root: true

parserOptions:
  sourceType: module

extends:
  - eslint:recommended

rules:
  quotes: [error, single, { avoidEscape: true, allowTemplateLiterals: true }]
  no-unused-vars: [error, { args: none }]
  no-trailing-spaces: [error]
  object-curly-spacing: [error, always]
  comma-dangle:
    - warn
    - arrays: always-multiline
      objects: always-multiline
      functions: only-multiline
  dot-notation: error
  prefer-const: warn
  no-extra-semi: off
