
name: Module Tests

on: [ push ]

env:
  CI: true

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 14.x, 16.x ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Module
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - name: Run test suite
      run: npm run test
