name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  CI: true

jobs:
  lint:
    uses: NicTool/.github/.github/workflows/lint.yml@main
    permissions:
      contents: read

  test:
    uses: NicTool/.github/.github/workflows/test.yml@main
    secrets: inherit
    permissions:
      contents: read
