
on: [ pull_request ]

name: Coverage

env:
  CI: true
  node_version: 14

jobs:

  coverage:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      name: Checkout Module
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ env.node_version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ env.node_version }}

    - name: npm install
      run: |
        npm install
        npm install --no-save c8 codecov

    - name: run coverage
      run: npx c8 --reporter=lcovonly npm run test
      env:
        NODE_ENV: cov

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}