
name: Lint

on: [ push ]

jobs:

  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14 ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout Module
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - name: Lint
      run: npm run lint

      env:
        CI: true