
name: publish

on:
  push:
    branches:
      - master

env:
  CI: true
  node_version: 14

jobs:

  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node.js ${{ env.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org/

      - run: npm install

      - run: npm run test

      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: GitHub Release
        uses: justincy/github-action-npm-release@2.0.1
        id: release

      - name: run coverage
        run: |
          npm install --no-save c8 codecov
          npx c8 --reporter=lcovonly npm run test
        env:
         NODE_ENV: cov

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
