name: publish

on:
  push:
    branches:
      - main
    paths:
      - package.json

env:
  CI: true

jobs:
  publish:
    uses: NicTool/.github/.github/workflows/publish.yml@main
    secrets: inherit