name: publish

on:
  push:
    branches:
      - master
    paths:
      - package.json

env:
  CI: true

jobs:
  publish:
    uses: NicTool/.github/.github/workflows/publish.yml@master
    secrets: inherit